config/routes.rb
TheSecret::Application.routes.draw do
  root :to => 'home#index'
  
  get "secret", to: "home#secret", as: :secret
  match 'auth/:provider/callback', to: 'authentications#omniauth', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  resource :session
  resource :profile
  resources :users
  resources :authentications
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :provider, :uid
  
  scope :from_omniauth, ->(auth) { where(provider: auth["provider"]).where(uid: auth["uid"]) }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :username
  
  has_many :authentications, dependent: :destroy
  
  validates :username, presence: true, uniqueness: true

  def validate_password?
    password.present? || password_confirmation.present?
  end
  
  has_secure_password
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.username = auth["info"]["nickname"]
      # Set a random string as password
      user.password = (0...8).map{65.+(rand(26)).chr}.join
      user.authentications.new(provider: auth["provider"], uid: auth["uid"])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :check_authorization
  
  private
  
  def check_authorization
    redirect_to(new_session_path) unless current_user
  end
  
  def current_user
    @user || User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_before_filter :check_authorization, only: :omniauth
  
  def omniauth
    authentication = Authentication.from_omniauth(env["omniauth.auth"]).first
    
    if authentication
      @user = authentication.user
      session[:user_id] = @user.id
      redirect_to secret_path, notice: "Welcome #{@user.username}"
    elsif current_user
      provider = env["omniauth.auth"]["provider"]
      uid = env["omniauth.auth"]["uid"]
      
      current_user.authentications.create!(provider: provider, uid: uid)
      redirect_to profile_url, notice: "#{provider.titleize} successfully added."
    else
      @user = User.create_from_omniauth(env["omniauth.auth"])
      session[:user_id] = @user.id
      redirect_to secret_path, notice: "Welcome #{@user.username}"
    end
    
    
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    
    if @authentication
      @authentication.destroy
      redirect_to profile_url, notice: "#{@authentication.provider.titleize} has been removed from your social networks."
    else
      redirect_to profile_url, alert: "#{@authentication.provider.titleize} could not be removed from your social networks."
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :check_authorization, only: :index
  
  def index
  end
  
  def secret
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
  end
  
  def update
    @user = current_user
    
    if @user.update_attributes(params[:user])
      redirect_to profile_url, notice: 'Password successfully updated.'
    else
      redirect_to profile_url, alert: 'Could not update your password.'
    end
  end
  
  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: 'Your account has been successfully destroyed. Good bye! And do not tell our secret!'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :check_authorization
  
  def new
  end
  
  def create
    @user = User.find_by_username(params[:username])

    redirect_to(new_session_path, alert: 'Could not find this user.') unless @user
    
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to secret_path, notice: "Welcome #{@user.username}"
    else
      redirect_to new_session_path, alert: 'Invalid credentials.'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "See you soon!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :check_authorization, only: [:new, :create]
  
  def index
    @users = User.includes(:authentications).all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to secret_path, notice: "Welcome aboard #{@user.username}!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Welcome to The Secret</h1>
  <% if current_user %>
    <p>You've discovered the secret!</p>
  <% else %>
    <p>Please signin or signup to discover who killed the cat.</p>
    <p>
      <a class="btn btn-primary btn-large" href="<%= new_session_path %>">
        Signin
      </a>
      <a class="btn btn-primary btn-large" href="<%= new_user_path %>">
        Signup
      </a>
    </p>
  <% end %>
</div>

app/views/home/secret.html.erb
<div class="page-header">
  <h1>Well... <small>Now you're cool enough to discover the secret</small></h1>
</div>

<div class="well">
  <%= image_tag 'curiosity.jpg' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>The Secret</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%= root_path %>">The Secret</a>
      <ul class="nav">
        <li class="active"><a href="<%= root_path %>">Home</a></li>
        <% if current_user %>
          <li><%= link_to 'The Secret', secret_path %></li>
          <li><%= link_to 'They Know The Secret', users_path %></li>
        <% else %>
          <li><a href="<%= new_session_path %>">Signin</a></li>
          <li><a href="<%= new_user_path %>">Signup</a></li>
        <% end %>
      </ul>
      
      <% if current_user %>
      <ul class="nav pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.username %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Profile', profile_path %></li>
            <li><%= link_to 'Logout', session_path, method: :delete %><li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</div>

<div class="container"> 
  
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>

app/views/profiles/show.html.erb
<h2>Social Networks</h2>
<table class="table table-striped">
  <% @user.authentications.each do |auth| %>
  <tr id="<%= auth.provider %>">
    <td>
      <%= image_tag(auth.provider + '.png') %>
      <%= auth.provider.titleize %>
    </td>
    <td><%= link_to 'Remove', authentication_path(auth), method: :delete %></td>
  </tr>
  <% end %>
</table>
<p>
  <%= link_to content_tag(:i, "", class: 'icon-twitter') + " Add Twitter", "/auth/twitter", class: 'btn', id: 'twitter-button' %>
  <%= link_to content_tag(:i, "", class: 'icon-facebook') + " Add Facebook", "/auth/facebook", class: 'btn', id: 'facebook-button' %>
  <%= link_to content_tag(:i, "", class: 'icon-github') + " Add Github", "/auth/github", class: 'btn', id: 'github-button' %>
</p>

<h2>Change your Password</h2>

<%= form_tag profile_path, method: :put, class: 'form-horizontal' do %>
  <fieldset>        
    <div class="control-group">
      <%= label_tag :user_password, 'Password', class: 'control-label' %>
      <div class="controls">
        <%= password_field_tag 'user[password]', '', placeholder: 'Your Password' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= label_tag :user_password_confirmation, 'Password Confirmation', class: 'control-label' %>
      <div class="controls">
        <%= password_field_tag 'user[password_confirmation]', '', placeholder: 'Password Confirmation' %>
      </div>
    </div>
    
    <div class="form-actions">
      <%= submit_tag 'Update', class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

<h2>Delete your Account</h2>

<%= link_to 'Delete My Account', profile_path, method: :delete, class: 'btn btn-danger', confirm: 'Are you sure you want to delete your account?' %>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>    
    <% if @user.errors.any? %>
      <div class="alert alert-error">
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="control-group">
      <%= f.label :username, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, placeholder: 'Your Username' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :password, class: 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, placeholder: 'Your Password' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :password_confirmation, class: 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>
      </div>
    </div>
    
    <div class="form-actions">
      <% if @user.new_record? %>
        <%= f.submit 'Signup', class: 'btn btn-primary' %>
      <% else %>
        <%= f.submit 'Update', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/users/index.html.erb
<h2>They Know The Secret</h2>
  
<table class="table stable-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Networks</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td>
          <% user.authentications.each do |auth| %>
            <%= image_tag auth.provider + '.png' %>
            &nbsp;
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<p>
  <%= link_to content_tag(:i, "", class: 'icon-twitter') + " Signup with Twitter", "/auth/twitter", class: 'btn' %>
  <%= link_to content_tag(:i, "", class: 'icon-facebook') + " Signup with Facebook", "/auth/facebook", class: 'btn' %>
  <%= link_to content_tag(:i, "", class: 'icon-github') + " Signup with Github", "/auth/github", class: 'btn' %>
</p>

<%= render 'form' %>